# 파이썬입문 겨울방학 특강 (3)

### import 

In [1]:
import numpy as np

### numpy공부 1단계(복습)

`-` 넘파이의 위력 

In [2]:
l=[1,2,3]
a=np.array(l) ## list()

`-` 사칙연산 브로드캐스팅 

In [8]:
a+1

array([2, 3, 4])

In [9]:
l+1

TypeError: can only concatenate list (not "int") to list

In [10]:
a*2

array([2, 4, 6])

In [11]:
l*2

[1, 2, 3, 1, 2, 3]

In [12]:
a-2

array([-1,  0,  1])

In [13]:
l-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [14]:
a/2

array([0.5, 1. , 1.5])

In [15]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 기타수학연산가능 

In [18]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [19]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

### numpy공부 2단계 

#### 연립1차방정식의 풀이 

`-` 아래의 연립방정식 고려 

$\begin{cases}
x + y = 2 \\
y + z = 2 \\ 
x + z = 2 
\end{cases}$

`-` 행렬표현은? 

$\begin{bmatrix}
1 &1& 0 \\ 
0 & 1 & 1 \\
1 & 0 & 1 
\end{bmatrix} 
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=\begin{bmatrix}
2 \\
2 \\
2 
\end{bmatrix}
$

In [20]:
A = [[1,1,0],[0,1,1],[1,0,1]] 
A

[[1, 1, 0], [0, 1, 1], [1, 0, 1]]

In [22]:
A2=np.array(A)
A2

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 1]])

`-` A의 원소인덱싱 

In [23]:
A[0][0], A[0][1], A[0][2]

(1, 1, 0)

In [24]:
A[1][0], A[1][1], A[1][2]

(0, 1, 1)

In [25]:
A[2][0], A[2][1], A[2][2]

(1, 0, 1)

`-` A2에서의 원소인덱싱 

In [28]:
A2[0][0], A2[0][1], A2[0][2]

(1, 1, 0)

In [29]:
A2[1][0], A2[1][1], A2[1][2]

(0, 1, 1)

In [30]:
A2[2][0], A2[2][1], A2[2][2]

(1, 0, 1)

`-` A2에서의 원소에 접근하는 또다른 방법 (numpy 신기술)

In [33]:
A2[0,0], A2[0,1], A2[0,2]

(1, 1, 0)

In [34]:
A2[1,0], A2[1,1], A2[1,2]

(0, 1, 1)

In [35]:
A2[2,0], A2[2,1], A2[2,2]

(1, 0, 1)

`-` 슬라이싱!

In [37]:
A2[0,:] ## R의 경우라면 A2[0,]

array([1, 1, 0])

In [38]:
A2[1,:] 

array([0, 1, 1])

In [39]:
A2[2,:] 

array([1, 0, 1])

`-` 연립방정식 문제를 다시 풀어보자. 

$\begin{bmatrix}
1 & 1 & 0 \\ 
0 & 1 & 1 \\
1 & 0 & 1 
\end{bmatrix} 
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=\begin{bmatrix}
2 \\
2 \\
2 
\end{bmatrix}
\quad \Longleftrightarrow \quad {\bf A} {\bf x} = {\bf b}
$

In [41]:
b=np.array([2,2,2])

In [46]:
np.linalg.inv(A2) @ b ## R로 치면 solve(A2) %*% b 

array([1., 1., 1.])

#### 인덱싱 

`-` 선언 

In [48]:
l=[11,22,33,44,55,66] 
a=np.array(l)
a

array([11, 22, 33, 44, 55, 66])

`-` 인덱스로 접근 

In [51]:
l[0],l[1],l[2],l[3],l[4],l[5]

(11, 22, 33, 44, 55, 66)

In [52]:
a[0],a[1],a[2],a[3],a[4],a[5]

(11, 22, 33, 44, 55, 66)

`-` `:` 이용 (슬라이싱) 

In [54]:
l[2:4] # index=2, index=3 (4는 포함되지 않음) 

[33, 44]

In [55]:
a[2:4]

array([33, 44])

너무 헷갈림.. 특히 마지막 원소를 포함해야할때!

In [59]:
l[2:6]

[33, 44, 55, 66]

In [60]:
a[2:6]

array([33, 44, 55, 66])

다행스럽게도 마지막의 6은 생략가능하다. 따라서 보통 아래와 같이 쓴다. 

In [61]:
l[2:]

[33, 44, 55, 66]

In [62]:
a[2:]

array([33, 44, 55, 66])

동일한 논리로 처음 인덱스도 생략가능하다. 

In [64]:
a[0:3], a[:3]

(array([11, 22, 33]), array([11, 22, 33]))

처음과 마지막을 둘다 생략한다면? 

In [65]:
a[:]

array([11, 22, 33, 44, 55, 66])

`-` 부울값을 이용한 인덱싱 

In [66]:
l=[11,22,33,44,55,66] 
a=np.array(l)
a

array([11, 22, 33, 44, 55, 66])

In [68]:
a[ [False, True, False, True, False, True] ]

array([22, 44, 66])

In [69]:
a<33

array([ True,  True, False, False, False, False])

In [70]:
a[a<33]

array([11, 22])

리스트는 안된다. 

In [74]:
l<33 ## 일단 여기서 막힘 

TypeError: '<' not supported between instances of 'list' and 'int'

#### reshape 

`-` reshape 

In [75]:
l = [11,22,33,44,55,66]
a = np.array(l)
a

array([11, 22, 33, 44, 55, 66])

In [76]:
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [78]:
a ## reshape은 a자체가 변화하지 않음 

array([11, 22, 33, 44, 55, 66])

In [79]:
b = a.reshape(2,3)
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` b를 다시 a처럼 바꾸고 싶다면? 

In [80]:
b.reshape(6)

array([11, 22, 33, 44, 55, 66])

In [81]:
b.flatten()

array([11, 22, 33, 44, 55, 66])

In [85]:
b.ravel()

array([11, 22, 33, 44, 55, 66])

In [84]:
b.reshape(-1)

array([11, 22, 33, 44, 55, 66])

### numpy공부 3단계 

`-` 2차원 array a,b를 선언하자. 

In [86]:
a=np.array([[11,22,33,44]]).reshape(2,2)
a

array([[11, 22],
       [33, 44]])

In [88]:
b=np.array([[11,22,33,44,55,66]]).reshape(2,3)
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` `a.` + TAB, `b.` + TAB 

In [90]:
a.shape, b.shape

((2, 2), (2, 3))

In [99]:
a.size, b.size

(4, 6)

In [100]:
a.itemsize, b.itemsize

(8, 8)

- ? 

In [102]:
a.strides, b.strides

((16, 8), (24, 8))

- ? 

***a의 형태***

In [103]:
a

array([[11, 22],
       [33, 44]])

***b의 형태***

In [104]:
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` itemsize와 strides의 의미를 유추하기 위해서 c,d를 더 만들어보자. 

In [105]:
c = np.array([11,22,33,44]).reshape(4,1)
d = np.array([11,22,33,44])

***c의 형태***

In [106]:
c

array([[11],
       [22],
       [33],
       [44]])

***d의 형태***

In [107]:
d

array([11, 22, 33, 44])

`-` a,b,c,d 속성비교 

In [109]:
a.shape, b.shape, c.shape, d.shape ## 차원 

((2, 2), (2, 3), (4, 1), (4,))

In [111]:
a.size, b.size, c.size, d.size ## 원소의 수

(4, 6, 4, 4)

In [112]:
a.itemsize, b.itemsize, c.itemsize, d.itemsize ## 항상 8? 

(8, 8, 8, 8)

In [115]:
a.strides, b.strides, c.strides, d.strides ## 차원이랑 관련이 있어보임.. + 8의 배수 

((16, 8), (24, 8), (8, 8), (8,))

In [116]:
a

array([[11, 22],
       [33, 44]])

`-` itemsize, strides는 무엇? 
- itemsize: 숫자하나를 저장하는 필요한 메모리 공간 
- strides: (다음 행으로 가기위해서 JUMP해야하는 메모리 공간수, 다음 열로 가기위해서 JUMP해야하는 메모리 공간수) 

`-` strides에 대한 추가해설 

**(오브젝트b)**

In [117]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [118]:
b.reshape(-1)

array([11, 22, 33, 44, 55, 66])

In [119]:
b.strides

(24, 8)

`-` itemsize는 항상 8이다?

In [120]:
e=np.array([11,22,33,44,55,66],dtype='int32')
e

array([11, 22, 33, 44, 55, 66], dtype=int32)

In [121]:
e.itemsize

4

In [122]:
e=e.reshape(2,3)
e

array([[11, 22, 33],
       [44, 55, 66]], dtype=int32)

In [123]:
e.strides

(12, 4)

### 참조 

`-` a를 선언, b는 a의 참조

In [147]:
a=np.array([[1,2],[3,4]])
b=a ## 참조 

In [148]:
a

array([[1, 2],
       [3, 4]])

In [149]:
b

array([[1, 2],
       [3, 4]])

In [150]:
a.shape

(2, 2)

In [151]:
b.shape

(2, 2)

`-` a의 shape을 바꾸어보자 $\to$ b도 같이 바뀐다 

In [152]:
a.shape = (4,)

In [153]:
a

array([1, 2, 3, 4])

In [154]:
b

array([1, 2, 3, 4])

In [155]:
id(a),id(b)

(139811809650992, 139811809650992)

### view 

`-` a를 선언, b는 a의 view

In [227]:
a=np.array([[1,2],[3,4]]) 
b=a.view() ## shallow copy 

In [171]:
a

array([[1, 2],
       [3, 4]])

In [172]:
b

array([[1, 2],
       [3, 4]])

In [173]:
a.shape

(2, 2)

In [174]:
b.shape

(2, 2)

In [175]:
a.shape= (4,1)

In [176]:
a

array([[1],
       [2],
       [3],
       [4]])

In [177]:
b

array([[1, 2],
       [3, 4]])

In [178]:
id(a), id(b)

(139811818705616, 139811818705424)

`-` 그런데.. 

In [179]:
a[0]=100

In [180]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [181]:
b

array([[100,   2],
       [  3,   4]])

`-` 출생의 비밀 

In [182]:
b

array([[100,   2],
       [  3,   4]])

In [183]:
b.base

array([[100],
       [  2],
       [  3],
       [  4]])

- ? 이거 바뀐 a아니야? 

In [184]:
id(b.base)

139811818705616

In [185]:
id(a)

139811818705616

`-` View 
- b가 a의 뷰라는 의미는, b가 a를 소스로하여 만들어진 오브젝트란 의미이다. 
- 따라서 이때 b.base는 a가 된다. 
- b는 자체적으로 데이터를 가지고 있지 않으며 a와 공유한다. 
- 이러한 의미에서 view를 shallow copy 라고 부른다. (가장 껍데기 구조만 복사하므로) 

`note1` 원본 ndarray의 일 경우는 .base가 None으로 나온다. 

In [188]:
a.base

`note2` b.base의 shpae과 b의 shape은 아무 관련없다. 

In [191]:
b.shape

(2, 2)

In [192]:
b.base.shape

(4, 1)

### copy 

`-` a를 선언, b는 a의 copy

In [193]:
a=np.array([[1,2],[3,4]])
b=a.copy()

In [195]:
id(a),id(b)

(139811818708208, 139811818707344)

`-` a의 shape을 바꿔도 b에는 적용되지 않음 

In [196]:
a.shape = (4,1)
a

array([[1],
       [2],
       [3],
       [4]])

In [197]:
b

array([[1, 2],
       [3, 4]])

`-` 그리고 a[0]의 값을 바꿔도 b에는 적용되지 않음. 

In [199]:
a[0]=100

In [200]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [201]:
b

array([[1, 2],
       [3, 4]])

`-` b의 출생을 조사해보니.. 

In [203]:
a.base,b.base

(None, None)

출생의 비밀은 없었다. 둘다 원본. 

***.copy의 한계(?)***

In [206]:
a=np.array([1,[1,2]],dtype='O')
a

array([1, list([1, 2])], dtype=object)

In [207]:
b=a.copy()

In [208]:
b

array([1, list([1, 2])], dtype=object)

In [209]:
a[0]=222

In [210]:
a

array([222, list([1, 2])], dtype=object)

In [211]:
b

array([1, list([1, 2])], dtype=object)

In [214]:
a[1][0]=333

In [215]:
a

array([222, list([333, 2])], dtype=object)

In [216]:
b

array([1, list([333, 2])], dtype=object)

***해결책: 더 깊은 복사***

In [217]:
import copy 

In [218]:
a=np.array([1,[1,2]],dtype='O')
b=copy.deepcopy(a)

In [219]:
a

array([1, list([1, 2])], dtype=object)

In [220]:
b

array([1, list([1, 2])], dtype=object)

In [221]:
a[0]=100

In [222]:
a,b

(array([100, list([1, 2])], dtype=object),
 array([1, list([1, 2])], dtype=object))

In [225]:
a[1][0]=200

In [226]:
a,b

(array([100, list([200, 2])], dtype=object),
 array([1, list([1, 2])], dtype=object))

일반적으로 넘파이를 이용할때 자주 사용하는 데이터 구조인 행렬, 텐서등을 이용하면 위와 같은 copy모듈은 불필요함 

### 별명, 뷰, 카피 

`-` test 함수 작성 

In [237]:
def test(a,b): 
    if id(a) == id(b): 
        print("별명")
    elif id(a) == id(b.base) or id(a.base)==id(b): 
        print("뷰")
    elif (id(a.base)!=id(None) and id(b.base)!=id(None)) and id(a.base) == id(b.base):
        print("공통의 base를 가짐")
    else: 
        print("카피, 혹은 아무 관련없는 오브젝트") 

`-` 잘 동작하나? 

(테스트1) 

In [238]:
a=np.array([1,2,3,4])
b=a

In [239]:
test(a,b)

별명


(테스트2) 

In [240]:
a=np.array([1,2,3,4])
b=a.view()

In [241]:
test(a,b)

뷰


(테스트3) 

In [242]:
a=np.array([1,2,3,4])
b=a.view()
c=a.view()

In [243]:
test(b,c)

공통의 base를 가짐


In [244]:
test(a,b)

뷰


In [245]:
test(a,c)

뷰


(테스트4) 

In [246]:
a=np.array([1,2,3,4])
b=a.copy()

In [247]:
test(a,b)

카피, 혹은 아무 관련없는 오브젝트


`-` 우리가 사용했던 어떠한 것들이 뷰가 나올지 카피가 나올지 사실 잘 모른다. 

In [248]:
a=np.array([1,2,3,4])
b=a[:3]

In [249]:
a

array([1, 2, 3, 4])

In [250]:
b

array([1, 2, 3])

In [251]:
test(a,b)

뷰


In [254]:
c=a[[0,1,2]]
c

array([1, 2, 3])

In [255]:
test(a,c)

카피, 혹은 아무 관련없는 오브젝트


`-` 

In [260]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [265]:
b=a.flatten()
c=a.ravel()
d=a.reshape(-1)

In [269]:
test(a,b)

카피, 혹은 아무 관련없는 오브젝트


In [270]:
test(a,c)

뷰


In [271]:
test(a,d)

뷰


In [272]:
test(c,d)

공통의 base를 가짐


In [273]:
test(b,c)

카피, 혹은 아무 관련없는 오브젝트
